# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"
  version = "1.17.0"

[[constraint]]
  name = "github.com/cloudfoundry-community/types-cf"
  source = "github.com/cloudfoundry-community/types-cf"
  revision = "0f57b598859da26e2ccd58dde308bc40e67fb25e"

[[constraint]]
  name = "github.com/go-martini/martini"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/martini-contrib/auth"
